class CreateTableNumbers < ActiveRecord::Migration[5.2]
  def change
    create_table :numbers do |n|
      n.date :draw_date
      n.integer :num_1
      n.integer :num_2
      n.integer :num_3
      n.integer :num_4
      n.integer :num_5
      n.integer :num_6
      n.integer :num_7
      n.integer :num_8
      n.integer :num_9
      n.integer :num_10
      n.integer :num_11
      n.integer :num_12
      n.integer :num_13
      n.integer :num_14
      n.integer :num_15
      n.integer :num_16
      n.integer :num_17
      n.integer :num_18
      n.integer :num_19
      n.integer :num_20
      n.integer :num_21
      n.integer :num_22
      n.integer :num_23
      n.integer :num_24
      n.integer :num_25
      n.integer :num_26
      n.integer :num_27
      n.integer :num_28
      n.integer :num_29
      n.integer :num_30
      n.integer :num_31
      n.integer :num_32
      n.integer :num_33
      n.integer :num_34
      n.integer :num_35
      n.integer :num_36
      n.integer :num_37
      n.integer :num_38
      n.integer :num_39
      n.integer :num_40
      n.integer :num_41
      n.integer :num_42
      n.integer :num_43
      n.integer :num_44
      n.integer :num_45
      n.integer :num_46
      n.integer :num_47
      n.integer :num_48
      n.integer :num_49
      n.integer :num_50
      n.integer :num_51
      n.integer :num_52
      n.integer :num_53
      n.integer :num_54
      n.integer :num_55
      n.integer :num_56
      n.integer :num_57
      n.integer :num_58
      n.integer :num_59
      n.integer :num_60
      n.integer :num_61
      n.integer :num_62
      n.integer :num_63
      n.integer :num_64
      n.integer :num_65
      n.integer :num_66
      n.integer :num_67
      n.integer :num_68
      n.integer :num_69
      
    end
  end
end
